name: Teardown

on:
  pull_request:
    types: [ closed ]
  workflow_dispatch:

jobs:
  job1:
    name: use deploy workflow to get deploy variables
    uses: ./.github/workflows/main.yaml

  job2:
    runs-on: ubuntu-latest
    name: Teardown
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}